import { TASKS, type Task } from "../data";

function TaskRow({ task, onToggle }: { task: Task; onToggle: (task: Task) => void }) {
  const done = task.status === "done";
  return <div className="flex items-center gap-4 px-5 py-4" style={{ borderBottom: "1px solid #F3F4F6" }}><button onClick={() => onToggle(task)} aria-label={done ? `Reopen ${task.title}` : `Complete ${task.title}`} className="w-5 h-5 rounded-md border flex items-center justify-center" style={{ borderColor: done ? "#7C5CFC" : "#D1D5DB", background: done ? "#7C5CFC" : "white" }}>{done && <span className="text-white text-[12px]">✓</span>}</button><span className="w-2 h-2 rounded-full" style={{ background: task.projectColor }} /><div className="flex-1 min-w-0"><p className={`text-[13px] font-semibold truncate ${done ? "line-through text-[#9CA3AF]" : "text-[#111827]"}`}>{task.title}</p><p className="text-[11.5px] text-[#9CA3AF] mt-0.5">{task.project} · Assigned to {task.assignee}</p></div>{task.overdue && !done && <span className="text-[10px] font-bold rounded-lg px-2 py-0.5 text-[#DC2626] bg-[#FEF2F2]">Overdue</span>}<span className="text-[11px] font-semibold rounded-full px-2.5 py-1 capitalize bg-[#F5F6FA] text-[#6B7280]">{task.status.replace("-", " ")}</span><span className="text-[11.5px] text-[#9CA3AF] whitespace-nowrap">{task.dueDate}</span></div>;
}

export default function TasksPage({ onToggle }: { onToggle: (task: Task) => void }) {
  const overdue = TASKS.filter((task) => task.overdue && task.status !== "done");
  return <div className="px-7 py-7" style={{ maxWidth: 1160, margin: "0 auto" }}><div className="mb-6"><h1 className="text-[22px] font-bold text-[#111827]">Tasks</h1><p className="text-[13px] mt-1 text-[#9CA3AF]">Click a checkbox to complete or reopen a task.</p></div><section className="mb-5 overflow-hidden rounded-2xl bg-white border border-[#EAECF0]"><header className="flex items-center justify-between px-5 py-3.5 border-b border-[#F3F4F6]"><div><p className="text-[13px] font-semibold text-[#111827]">Overdue tasks</p><p className="text-[11.5px] text-[#9CA3AF]">Needs attention before other planned work.</p></div><span className="rounded-full px-2.5 py-1 text-[11px] font-semibold text-[#DC2626] bg-[#FEF2F2]">{overdue.length}</span></header>{overdue.length ? overdue.map((task) => <TaskRow key={task.id} task={task} onToggle={onToggle} />) : <div className="flex items-center gap-2 px-5 py-5 text-[12.5px] text-[#9CA3AF]"><span>No overdue tasks. You’re on track.</span><span aria-label="On track" className="flex h-5 w-5 items-center justify-center rounded-full bg-[#DCFCE7] text-[12px] font-bold text-[#16A34A]">✓</span></div>}</section><section className="bg-white rounded-2xl overflow-hidden border border-[#EAECF0]"><header className="px-5 py-3.5 border-b border-[#F3F4F6]"><p className="text-[13px] font-semibold text-[#111827]">All tasks</p></header>{TASKS.map((task) => <TaskRow key={task.id} task={task} onToggle={onToggle} />)}</section></div>;
}
